const PLAYER_MIN_ATTACK_POINTS = 5;
const PLAYER_MAX_ATTACK_POINTS = 10;

const PLAYER_MIN_SPECIAL_ATTACK_POINTS = 9;
const PLAYER_MAX_SPECIAL_ATTACK_POINTS = 14;

const PLAYER_MIN_HEAL_POINTS = 8;
const PLAYER_MAX_HEAL_POINTS = 11;

const PLAYER_HEALTH_POTIONS_NUMBER = 5;

const MONSTER_MIN_ATTACK_POINTS = 7;
const MONSTER_MAX_ATTACK_POINTS = 12;

export default {
    PLAYER_MIN_ATTACK_POINTS,
    PLAYER_MAX_ATTACK_POINTS,
    PLAYER_MIN_SPECIAL_ATTACK_POINTS,
    PLAYER_MAX_SPECIAL_ATTACK_POINTS,
    PLAYER_MIN_HEAL_POINTS,
    PLAYER_MAX_HEAL_POINTS,
    PLAYER_HEALTH_POTIONS_NUMBER,
    MONSTER_MIN_ATTACK_POINTS,
    MONSTER_MAX_ATTACK_POINTS
};